### ISSUE TITLE
Make the button "Take the quiz to know" visible

### ISSUE THREAD

**Issue by sushrut111** [sushrut111/corona-virus-questionnaire#13]
- Hosted at [https://sushrut111.github.io/corona-virus-questionnaire/](https://sushrut111.github.io/corona-virus-questionnaire/)
- This is a simple react application which asks user some questions and based on the responses, tell him whether they should see a doctor in regard of COVID-19
- The UI is bit rusty, the take test button is not very visible like a button but just looks like a block like others on the page.
- The button needs to be fixed to have an impression as a button so that user can click on it - basically, you have to edit the region's CSS to show the cursor as a pointer.
![Screenshot 2020-10-04 at 3 43 09 PM](https://user-images.githubusercontent.com/11269256/95012782-f0b1b980-0658-11eb-89d6-8a3bf7419eaa.png)

**Comment by gaurang7goel** [comment]
Hi, I can try to do it.

**Comment by CLOEI** [comment]
may i?, and i just need to add cursor styling to that container am i correct?

**Comment by sagar-monga** [comment]
Can I work on this?

**Comment by PiyushNadoda** [comment]
Can I work on this issue #4   ? I will change it's color to white and add some hover effect. I'll add box-shadow or change size of button on hover to make it visually appealing.

**Comment by sushrut111** [comment]
@CLOEI @sagar-monga @PiyushNadoda all of you please feel free to work on it and create a PR. Feel free to improve other things if you feel any need to. I will be happy to review the changes and incorporate them.

@CLOEI , @PiyushNadoda Your ideas sound great, please go ahead.

**Comment by sagar-monga** [comment]
![image](https://user-images.githubusercontent.com/50130301/135580391-9e9e7ae4-3c64-412e-8277-eaded68cd6c6.png)
Facing problem in cloning the repo
Tried using GitHub desktop, but I'm getting the same problem.

**Comment by PiyushNadoda** [comment]
@sushrut111 Improved your important link section. Check that out.

**Comment by sushrut111** [comment]
@PiyushNadoda  thank you! I will check it out soon.

**Comment by sushrut111** [comment]
@sagar-monga try now

**Comment by ishikajn8126** [comment]
Hey @sushrut111 
Can I also work on this issue?

**Comment by sushrut111** [comment]
@ishikajn8126 sure

**Comment by Devenkapoor7303** [comment]
@sushrut111  I have created a PR can you please check this out? 
https://github.com/sushrut111/corona-virus-questionnaire/pull/16

**Comment by sagar-monga** [comment]
> @sagar-monga try now

Facing same issue now too

**Comment by sushrut111** [comment]
@Devenkapoor7303 I have commented on the PR

**Comment by ishikajn8126** [comment]
@sushrut111 i'm not able to find where css is written for this element..
can you plz let me know that

**Comment by Devenkapoor7303** [comment]
@ishikajn8126 I think he is using Bulma css It is a css framework.

**Comment by sushrut111** [comment]
@ishikajn8126 Here is the corresponding html - https://github.com/sushrut111/corona-virus-questionnaire/blob/master/src/app/containers/Landing.js#L10-L19
There is no custom css added yet. But you can add a clas in the css file and import that file to the file referenced above and use the class on the div in discussion.

**Comment by ayasahmad63** [comment]
hey, @sushrut111  can I work on it??

**Comment by PiyushNadoda** [comment]
@sushrut111 solved conflict you can merge now.

**Comment by sushrut111** [comment]
@ayasahmad63 The button stuff is done now. If you think you can improve it further, please create a PR.
