### ISSUE TITLE
Add a back or home button to go back to homepage during the test

### ISSUE THREAD

**Issue by sushrut111** [sushrut111/corona-virus-questionnaire#17]
Currently clicking on the title banner takes you back to main page but that is not very intuitive.
![image](https://user-images.githubusercontent.com/11269256/135617529-e3804062-0f71-48d9-bc7e-058f58d9e41d.png)

It will be great to have a back button.

**Comment by vivekkj123** [comment]
Pls assign this to me

**Comment by Devenkapoor7303** [comment]
@sushrut111 So do you want to change the CSS of the banner.

**Comment by sushrut111** [comment]
@vivekkj123 Please feel free to start working on it a create a pull request.
@Devenkapoor7303 not exactly, I am thinking of a back button .

**Comment by Devenkapoor7303** [comment]
@sushrut111 can I also work on it?

**Comment by sushrut111** [comment]
Sure @Devenkapoor7303

**Comment by joshi-kaushal** [comment]
Is this issue still on? I'd love to work :)

**Comment by sushrut111** [comment]
@joshi-kaushal sure, please take it up!

**Comment by Devenkapoor7303** [comment]
@sushrut111 can you please check the PR.

**Comment by joshi-kaushal** [comment]
@Devenkapoor7303 did you solve it?

**Comment by Devenkapoor7303** [comment]
Yeah

**Comment by joshi-kaushal** [comment]
@sushrut111 I glanced through the entire codebase and saw that our code is unreadable and not supporting good coding practices. Would it be okay if I add ESLint to the project?

**Comment by sushrut111** [comment]
@joshi-kaushal Sure, please go ahead. If you want to add tests, you can do that too.

**Comment by joshi-kaushal** [comment]
@sushrut111 can you please create an issue and assign it to me?

**Comment by sushrut111** [comment]
@joshi-kaushal please feel free to create issue specific to what you will be working on.
