### ISSUE TITLE
Make the button to take the test visible

### ISSUE THREAD

**Issue by sushrut111** [sushrut111/corona-virus-questionnaire#4]
- Hosted at [https://sushrut111.github.io/corona-virus-questionnaire/](https://sushrut111.github.io/corona-virus-questionnaire/)
- This is a simple react application which asks user some questions and based on the responses, tell him whether they should see a doctor in regard of COVID-19
- The UI is bit rusty, the take test button is not very visible like a button but just looks like a block like others on the page.
- The button needs to be fixed to have an impression as a button so that user can click on it.
![Screenshot 2020-10-04 at 3 43 09 PM](https://user-images.githubusercontent.com/11269256/95012782-f0b1b980-0658-11eb-89d6-8a3bf7419eaa.png)

**Comment by lafeo** [comment]
i can help you out here

**Comment by sushrut111** [comment]
Sure, please go ahead and contribute!

**Comment by sushrut111** [comment]
I have assigned this to you @lafeo

**Comment by sushrut111** [comment]
Others are welcome to contribute and enhance the UI.

**Comment by lafeo** [comment]
aight sounds good gimme a 3-4 days
